services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-go_backend}
      - DB_PORT=${DB_PORT:-5432}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-8080}
    networks:
      - go-network
    restart: unless-stopped

networks:
  go-network:
    driver: bridge
